config/routes.rb
Rails.application.routes.draw do
  

  
  devise_for :users
  root :to=> "books#new"
  resources :books do
  	resources :comments
  end
  resources :pics do 
  	resources :comments
  end
   root :to=> "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
end

app/models/pic.rb
class Pic < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

   def load_commentable
  	resources, id = request.path.split('/')[1,2]
  	@commentable = resources.singularize.classify.constantize.find(id)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
    @commentable = @book
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  def book_params
    params.require(:book).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :load_commentable

  def new
  	@comment = @commentable.comments.new

  end
  def create
  	@comment = @commentable.comments.new(comment_params)
  	if @comment.save
  		redirect_to @commentable
  	else
  		render 'new'
  	end
  end

  def index
  	@comments = @commentable.comments

  end

  private
  
  def comment_params
  	params.require(:comment).permit(:content, :commentable_id, :commentable_type)
  end

 
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  before_action :load_commentable, only: [:show]

  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
    @commentable = @pic
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(pic_params)

    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url, notice: 'Pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:name, :size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Create Blog</h1>
<%= form_for @book do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br><br>

  <%= f.submit 'update' %>
 <% end %>

app/views/books/index.html.erb
<p class="para"><%= link_to 'book', new_book_path %> | 
<%= link_to 'pic', new_pic_path %></p><br>

<h1>Blogs</h1>

<% @books.each do |f| %>

	<h1><%= link_to  f.name, book_path(f) %></h1>
	<p><%= f.description %></p>

	<%= link_to 'edit', edit_book_path(f) %> |
	<%= link_to 'delete', f, :method=> :delete %>
	<hr>
<% end %>
<%= link_to 'new', new_book_path %>

app/views/books/new.html.erb
<h1>Create Blog</h1>
<%= form_for @book do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br><br>

  <%= f.submit %>
 <% end %>

app/views/books/show.html.erb
<h1>show</h1>
<body>
<h1><%= @book.name %></h1>
<p><%= @book.description %></p><br><br><hr>

<%= render 'comments/comment' %>
<%= render 'comments/form' %>
</body>

app/views/comments/_comment.html.erb
<h1>Comments</h1>
<% @comments.each do |s| %>
	<%= s.content %><hr>
<% end %> 

app/views/comments/_form.html.erb
<%= form_for ([@commentable, @comment]) do |s| %>
	<%= s.label :content %>
	<%= s.text_area :content %><br><br>
	<%= s.submit %>
	<%= link_to 'back', books_path %> 
<% end %>

app/views/comments/index.html.erb
<%= render 'comment' %>
<br>

<%= link_to 'New Comment', [:new, @commentable, :comment] %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <%= yield %>
  </body>
</html>

app/views/pics/_form.html.erb
<%= form_with(model: pic, local: true) do |form| %>
  <% if pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pic_name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size, id: :pic_size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing Pic</h1>

<%= render 'form', pic: @pic %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pics.each do |pic| %>
      <tr>
        <td><%= pic.name %></td>
        <td><%= pic.size %></td>
        <td><%= link_to 'Show', pic %></td>
        <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
        <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New Pic</h1>

<%= render 'form', pic: @pic %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pic.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @pic.size %>
</p>
<%= render 'comments/comment' %>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>